React week8
olgakahraman/ctd-react-app pull request #7
Opened 2024-08-06 23:53 UTC by olgakahraman

2024-08-12 21:26 UTC, alexgs requested changes
This was a challenging week! You're very close, just need some changes to make it work correctly. Please let me know if you have any questions.

2024-08-12 21:26 UTC, alexgs commented on src/App.jsx
> +	const [isLoading, setIsLoading] = "true";
Here, you're setting the value of `isLoading` to the string "true," not the Boolean `true`. You need to use the Boolean value.

2024-08-12 21:26 UTC, alexgs commented on src/App.jsx
> +				resolve({ data: { todoList: [] } }, 2000).then(
Loading the persisted state from local storage should happen here.

2024-08-12 21:26 UTC, alexgs commented on src/App.jsx
>  	});
This `useEffect` call doesn't have a list of dependencies.

2024-08-12 21:26 UTC, alexgs commented on src/App.jsx
> +	});
This `useEffect` call doesn't have a list of dependencies

2024-08-14 14:14 UTC, olgakahraman commented
fixed some problems

2024-08-19 12:03 UTC, alexgs approved these changes
Great work!

2024-08-21 15:33 UTC, merged